//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAppWeatherForecast.WindowsForm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f9a5f827-d5fe-4a3d-b4e6-703f49a4a6c7")]
        public string ClientToken {
            get {
                return ((string)(this["ClientToken"]));
            }
            set {
                this["ClientToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5209")]
        public string BaseUrl {
            get {
                return ((string)(this["BaseUrl"]));
            }
            set {
                this["BaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/alldata")]
        public string AllSynopticDataEndpoint {
            get {
                return ((string)(this["AllSynopticDataEndpoint"]));
            }
            set {
                this["AllSynopticDataEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/towns")]
        public string TownsListEndpoint {
            get {
                return ((string)(this["TownsListEndpoint"]));
            }
            set {
                this["TownsListEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pełna informacja")]
        public string FullInfoTab {
            get {
                return ((string)(this["FullInfoTab"]));
            }
            set {
                this["FullInfoTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wybrane miasto")]
        public string TownInfoTab {
            get {
                return ((string)(this["TownInfoTab"]));
            }
            set {
                this["TownInfoTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mapa Polski")]
        public string PolandMapTab {
            get {
                return ((string)(this["PolandMapTab"]));
            }
            set {
                this["PolandMapTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Akcja")]
        public string ActionMenu {
            get {
                return ((string)(this["ActionMenu"]));
            }
            set {
                this["ActionMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("O autorze")]
        public string AuthorMenu {
            get {
                return ((string)(this["AuthorMenu"]));
            }
            set {
                this["AuthorMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wyjście")]
        public string ExitMenu {
            get {
                return ((string)(this["ExitMenu"]));
            }
            set {
                this["ExitMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pobierz aktualne informacje pogodowe")]
        public string GetFullDataButton {
            get {
                return ((string)(this["GetFullDataButton"]));
            }
            set {
                this["GetFullDataButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wybierz miasto")]
        public string ChooseTownLabel {
            get {
                return ((string)(this["ChooseTownLabel"]));
            }
            set {
                this["ChooseTownLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/alldatatown")]
        public string AllDataTownEndpoint {
            get {
                return ((string)(this["AllDataTownEndpoint"]));
            }
            set {
                this["AllDataTownEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/synopticdata")]
        public string SynopticDataUrl {
            get {
                return ((string)(this["SynopticDataUrl"]));
            }
            set {
                this["SynopticDataUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/alldatatowns")]
        public string AllDataTownsEndpoint {
            get {
                return ((string)(this["AllDataTownsEndpoint"]));
            }
            set {
                this["AllDataTownsEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/townstemperatures")]
        public string TownsTemperaturesEndpoint {
            get {
                return ((string)(this["TownsTemperaturesEndpoint"]));
            }
            set {
                this["TownsTemperaturesEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/townspressures")]
        public string TownsPressuresEndpoint {
            get {
                return ((string)(this["TownsPressuresEndpoint"]));
            }
            set {
                this["TownsPressuresEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/townshumidities")]
        public string TownsHumiditiesEndpoint {
            get {
                return ((string)(this["TownsHumiditiesEndpoint"]));
            }
            set {
                this["TownsHumiditiesEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/serverstatus")]
        public string ServerStatusEndpoint {
            get {
                return ((string)(this["ServerStatusEndpoint"]));
            }
            set {
                this["ServerStatusEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/ping")]
        public string ServerPingEndpoint {
            get {
                return ((string)(this["ServerPingEndpoint"]));
            }
            set {
                this["ServerPingEndpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/api/access")]
        public string AccesUrl {
            get {
                return ((string)(this["AccesUrl"]));
            }
            set {
                this["AccesUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Temperatura")]
        public string GetTemperaturesDataButton {
            get {
                return ((string)(this["GetTemperaturesDataButton"]));
            }
            set {
                this["GetTemperaturesDataButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ciśnienie")]
        public string GetPressuresDataButton {
            get {
                return ((string)(this["GetPressuresDataButton"]));
            }
            set {
                this["GetPressuresDataButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wilgotność")]
        public string GetHumidityDataButton {
            get {
                return ((string)(this["GetHumidityDataButton"]));
            }
            set {
                this["GetHumidityDataButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pogoda INFO")]
        public string AppTitle {
            get {
                return ((string)(this["AppTitle"]));
            }
            set {
                this["AppTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wczytaj aktualne dane")]
        public string LoadDataLabel {
            get {
                return ((string)(this["LoadDataLabel"]));
            }
            set {
                this["LoadDataLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...sprawdzanie dostępu")]
        public string CheckingAccess {
            get {
                return ((string)(this["CheckingAccess"]));
            }
            set {
                this["CheckingAccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Autor: Łukasz Krzos")]
        public string AuthorLabel {
            get {
                return ((string)(this["AuthorLabel"]));
            }
            set {
                this["AuthorLabel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Błąd sprawdzania pingu")]
        public string MessagePingError {
            get {
                return ((string)(this["MessagePingError"]));
            }
            set {
                this["MessagePingError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Błąd sprawdzania dostępności")]
        public string MessageAvibilityError {
            get {
                return ((string)(this["MessageAvibilityError"]));
            }
            set {
                this["MessageAvibilityError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Serwer pogodowy nie jest dostępny! Spróbuj później!")]
        public string MessageServerNotResponse {
            get {
                return ((string)(this["MessageServerNotResponse"]));
            }
            set {
                this["MessageServerNotResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Błąd pobierania danych synoptycznych")]
        public string MessageGetSynopticDataError {
            get {
                return ((string)(this["MessageGetSynopticDataError"]));
            }
            set {
                this["MessageGetSynopticDataError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Błąd deserializacji danych!")]
        public string MessageDataDeserializationError {
            get {
                return ((string)(this["MessageDataDeserializationError"]));
            }
            set {
                this["MessageDataDeserializationError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Brak danych.")]
        public string MessageNotDataFound {
            get {
                return ((string)(this["MessageNotDataFound"]));
            }
            set {
                this["MessageNotDataFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Autorem aplikacji jest Łukasz Krzos. Może chesz go wesprzeć?")]
        public string AuthorInfo {
            get {
                return ((string)(this["AuthorInfo"]));
            }
            set {
                this["AuthorInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dziękuję :)")]
        public string HappyFace {
            get {
                return ((string)(this["HappyFace"]));
            }
            set {
                this["HappyFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(":(")]
        public string SadFace {
            get {
                return ((string)(this["SadFace"]));
            }
            set {
                this["SadFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Czy na pewno chcesz wyjść z aplikacji?")]
        public string ExitInfo {
            get {
                return ((string)(this["ExitInfo"]));
            }
            set {
                this["ExitInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data aktualizacji")]
        public string ActualizationData {
            get {
                return ((string)(this["ActualizationData"]));
            }
            set {
                this["ActualizationData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data odczytu")]
        public string LoadDate {
            get {
                return ((string)(this["LoadDate"]));
            }
            set {
                this["LoadDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wczytano temperaturę.")]
        public string TemperatudeLoaded {
            get {
                return ((string)(this["TemperatudeLoaded"]));
            }
            set {
                this["TemperatudeLoaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wczytano ciśnienie.")]
        public string PressureLoaded {
            get {
                return ((string)(this["PressureLoaded"]));
            }
            set {
                this["PressureLoaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wczytano wilgotność.")]
        public string HumidityLoaded {
            get {
                return ((string)(this["HumidityLoaded"]));
            }
            set {
                this["HumidityLoaded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Serwer pogodowy nie odpowiada!")]
        public string MessageServerNotWorks {
            get {
                return ((string)(this["MessageServerNotWorks"]));
            }
            set {
                this["MessageServerNotWorks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OK")]
        public string ServerStatusOk {
            get {
                return ((string)(this["ServerStatusOk"]));
            }
            set {
                this["ServerStatusOk"] = value;
            }
        }
    }
}
